config/routes.rb
Rails.application.routes.draw do
  get 'report/tc2'
  post 'report/track_by_create'

  get 'report/tc1'
  get 'report/pizza1'
  get 'report/bar1'
  get 'report/bar2'

  get 'report/room'
  get 'report/responsible'

  get 'users', to: 'users#index'

  get 'user/:id', to: 'users#show'

  devise_for :users
  resources :patrimonies

  resources :responsibles

  resources :rooms

  get 'home/index'

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  def index
    @users = User.all
  end

  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:users).permit(:name, :email)
  end

end

app/views/users/index.html.erb
<h1>Listando usuários</h1>

<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>E-mail</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Mostrar', '/user/'+user.id.to_s %></td>
       <!-- <td><%#= link_to 'Editar', edit_users_path(users) %></td>
        <td><%#= link_to 'Deletar', users, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'Novo Usuário', new_user_path %>

app/views/users/show.html.erb
<table class="table table-bordered">
  <tr>
    <th>Email</th>
    <td><%= @user.email%></td>
  </tr>
</table>

<%= link_to 'Voltar', users_path, class: "btn btn-default" %>