config/routes.rb
Rails.application.routes.draw do
  get 'report/tc2'
  post 'report/track_by_create'

  get 'report/tc1'
  get 'report/pizza1'
  get 'report/bar1'
  get 'report/bar2'

  get 'report/room'
  get 'report/responsible'

  get 'users', to: 'users#index'

  get 'user/:id', to: 'users#show'

  devise_for :users
  resources :patrimonies

  resources :responsibles

  resources :rooms

  get 'home/index'

  root 'home#index'

end

app/models/responsible.rb
class Responsible < ActiveRecord::Base
  has_many :patrimonies

  validates_uniqueness_of :identifier, :email, :tel

end

app/controllers/responsibles_controller.rb
class ResponsiblesController < ApplicationController
  before_action :set_responsible, only: [:show, :edit, :update, :destroy]
  before_action :set_track, only: [:create, :update, :destroy]

  def set_track
    @track = Track.new({model: "Responsáveis", action: action_name.to_s, user_id: current_user.id})
    @track.save
  end

  # GET /responsibles
  # GET /responsibles.json
  def index
    @responsibles = Responsible.all
  end

  # GET /responsibles/1
  # GET /responsibles/1.json
  def show
  end

  # GET /responsibles/new
  def new
    @responsible = Responsible.new
  end

  # GET /responsibles/1/edit
  def edit
  end

  # POST /responsibles
  # POST /responsibles.json
  def create
    @responsible = Responsible.new(responsible_params)
    @responsible.identifier = Digest::MD5.hexdigest(@responsible.email.to_s)
    respond_to do |format|
      if @responsible.save
        format.html { redirect_to @responsible, notice: 'Responsável criado com sucesso.' }
        format.json { render :show, status: :created, location: @responsible }
      else
        format.html { render :new }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responsibles/1
  # PATCH/PUT /responsibles/1.json
  def update
    respond_to do |format|
      if @responsible.update(responsible_params)
        format.html { redirect_to @responsible, notice: 'Responsável atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @responsible }
      else
        format.html { render :edit }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsibles/1
  # DELETE /responsibles/1.json
  def destroy
    @responsible.destroy
    respond_to do |format|
      format.html { redirect_to responsibles_url, notice: 'Responsável deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_responsible
      @responsible = Responsible.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def responsible_params
      params.require(:responsible).permit(:identifier, :name, :email, :birth, :address, :tel)
    end
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/views/responsibles/_form.html.erb
<%= form_for(@responsible) do |f| %>
  <% if @responsible.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@responsible.errors.count, "error") %> proibiu o salvamento deste responsável:</h2>

      <ul>
      <% @responsible.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nome:" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "E-Mail:" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label "Data de Nascimento:" %><br>
    <%= f.date_select :birth, :as => :date, :label=>"Data de Nascimento",:order => [:day, :month, :year], :start_year => (Date.current.year-18), :use_month_names => ["Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"], :end_year => (Date.current.year-90), :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label "Endereço:" %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label "Telefone:" %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="actions">
    <%= f.submit "Criar Responsável", class: "btn btn-success" %>
  </div>
<% end %>

app/views/responsibles/edit.html.erb
<h1>Editar Responsável</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @responsible, class: "btn btn-default btn-xs"  %>
<%= link_to 'Voltar', responsibles_path, class: "btn btn-default btn-xs"  %>

app/views/responsibles/index.html.erb
<h1>Responsáveis Cadastrados</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>E-Mail</th>
      <th>Data de Nascimento</th>
      <th>Endereço</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responsibles.each do |responsible| %>
      <tr>
        <td><%= responsible.name %></td>
        <td><%= responsible.email %></td>
        <td><%= responsible.birth %></td>
        <td><%= responsible.address %></td>
        <td><%= responsible.tel %></td>
        <td><%= link_to 'Mostrar', responsible %></td>
        <td><%= link_to 'Editar', edit_responsible_path(responsible) %></td>
        <td><%= link_to 'Excluir', responsible, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Responsável', new_responsible_path, class: "btn btn-default" %>

app/views/responsibles/new.html.erb
<h1>Novo Responsável</h1>

<%= render 'form' %>

<%= link_to 'Voltar', responsibles_path, class: "btn btn-default btn-xs"  %>

app/views/responsibles/show.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>Nome</th>
    <td><%= @responsible.name %></td>
  </tr>
  <tr>
    <th>Identificador</th>
    <td><%= @responsible.identifier %></td>
  </tr>
  <tr>
    <th>E-Mail</th>
    <td><%= @responsible.email %></td>
  </tr>
  <tr>
    <th>Data de Nascimento</th>
    <td><%= @responsible.birth %></td>
  </tr>

  <tr>
    <th>Endereço</th>
    <td><%= @responsible.address %></td>
  </tr>
  <tr>
    <th>Telefone</th>
    <td><%= @responsible.tel %></td>
  </tr>
</table>

<%= link_to 'Editar', edit_responsible_path(@responsible), class: "btn btn-default" %>
<%= link_to 'Voltar', responsibles_path, class: "btn btn-default" %>