config/routes.rb
Rails.application.routes.draw do
  get 'report/tc2'
  post 'report/track_by_create'

  get 'report/tc1'
  get 'report/pizza1'
  get 'report/bar1'
  get 'report/bar2'

  get 'report/room'
  get 'report/responsible'

  get 'users', to: 'users#index'

  get 'user/:id', to: 'users#show'

  devise_for :users
  resources :patrimonies

  resources :responsibles

  resources :rooms

  get 'home/index'

  root 'home#index'

end

app/views/layouts/_alerts.html.erb
<% if notice %><p class="alert alert-success"><%= notice%></p><% end %>
<% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <a class="navbar-brand" href="/"></a>
        <li><%= link_to 'Home', home_index_path %></li>
        <li><%= link_to 'Patrimônios', patrimonies_path %></li>
        <li><%= link_to 'Responsáveis', responsibles_path %></li>
        <li><%= link_to 'Salas', rooms_path %></li>
        <li><%= link_to 'Usuários', '/users' %></li>



        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Relatórios <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Patrimônio / Sala', report_pizza1_path %></li>
            <li><%= link_to 'Patrimônio / Responsável', report_bar1_path %></li>
            <li><%= link_to 'Patrimônio / Status', report_bar2_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Ações por usuário', report_tc1_path %></li>
          </ul>
        </li>



        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Conta <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Configurações de Conta', "#" %></li>
            <li class="divider"></li>
            <% if current_user %>
                <li><%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "" %></li>
            <% end %>
          </ul>
        </li>





      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watchman</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="/bootstrap/css/bootstrap.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="/bootstrap/js/bootstrap.js"></script>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render partial: 'layouts/header' if current_user%>
    <%= render partial: 'layouts/alerts' %>



    <% if controller_name != 'home'  %>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
    <% end %>

    <%= yield %>

    <% if controller_name != 'home'  %>
              </div>
          </div>
        </div>
    <% end %>


    <%= render partial: 'layouts/footer' %>

    <!-- Referências JS -->
   
</body>
</html>